apiVersion: v1
kind: Service
metadata:
  name: kimai-service
  namespace: kimai
  labels:
    app: kimai
    env: prod
spec:
  ports:
  - port: 8001
  selector:
    app: kimai
    env: prod
  clusterIP: None
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kimai-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kimai-service
            port:
              number: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kimai-deployment
  namespace: kimai
  labels:
    app: kimai
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kimai
      env: prod
  template:
    metadata:
      labels:
        app: kimai
        env: prod
    spec:
      containers:
      - name: kimai
        image: kimai/kimai2:apache-1.14.3-prod
        env:
          - name: DATABASE_URL
            value: "mysql://<USER>:<PASSWORD>@mysql.kimai.svc.cluster.local:3306/<KIMAI_DB>"
          - name: TRUSTED_HOSTS
            value: localhost,<INGRESS_IP>
        ports:
        - containerPort: 8001
        resources:
          requests:
            cpu: "850m"
            memory: "1200Mi"
          limits:
            cpu: "1000m"
            memory: "1500Mi"